apiVersion: v1
kind: Pod
metadata:
  name: http-echo-app
spec:
  containers:
    - name: http-echo
      image: hashicorp/http-echo
      imagePullPolicy: Always # Always|IfNotPresent
      args:
        - "-text=hello"
      ports:
        - containerPort: 5678
